### ISSUE TITLE
[FEATURE] Start the Community Builders landing page 

### ISSUE THREAD

**Issue by vinzvinci** [community-builders/community-builders.github-io#1]
Thanks @Simperfy for helping on this design. Only Team Web3 can work with this issue as for their recognition on contributing to @web3community & @dev-protocol community. Feel free to get this green square📗. 

We will launch the Community Builders on Monday, so hopefully it can be done on Sunday night (GMT+8). 

If no one work here on Saturday, I'll be taking this issue.

## Implementation

The design is here

https://www.figma.com/file/ZWhbYOGvx88xqLmRhCcwQX/Community-Builders-Website?node-id=0%3A1

#### Tech Stacks
- TailwindUI
- Any tech stack will do (Next.js, React, Astro)
- You can suggest below on what will u use

**Comment by AbhinavMV** [comment]
Will use the same code on devprotocol website and add an extra page. 
Let me know if any other changes need to be done. 😄

**Comment by vinzvinci** [comment]
Awesome, thank you @AbhinavMV!
